# Generated by Django 5.0.6 on 2024-07-30 04:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=50, null=True, samples=None),
        ),
    ]
