# Generated by Django 5.0.6 on 2024-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
