# Generated by Django 5.0.6 on 2024-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_color_remove_products_color_categories_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='color_name',
        ),
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
