# Generated by Django 5.0.6 on 2024-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_products_quantity_alter_products_name_add_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
