# Generated by Django 5.0.6 on 2024-08-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
