# Generated by Django 5.0.6 on 2024-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_rename_contact_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='color_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='size_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_color',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='my_app.color_cart'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='my_app.size_cart'),
        ),
    ]
