# Generated by Django 5.0.6 on 2024-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_color_cart_size_cart_remove_products_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
