# Generated by Django 5.0.6 on 2024-08-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_rename_products_id_wish_list_products_id1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish_list',
            old_name='products_id1',
            new_name='products_id',
        ),
        migrations.RenameField(
            model_name='wish_list',
            old_name='user_id1',
            new_name='user_id',
        ),
    ]
