# Generated by Django 5.0.6 on 2024-08-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_rename_products_id1_wish_list_products_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish_list',
            old_name='image',
            new_name='img',
        ),
    ]
