# Generated by Django 5.0.6 on 2024-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_rename_image_wish_list_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuopon_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('one_time_use', models.BooleanField(default=False)),
            ],
        ),
    ]
