# Generated by Django 5.0.6 on 2024-08-31 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_rename_cuopon_code_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField()),
                ('pin_code', models.IntegerField()),
                ('street_address', models.TextField()),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.signup')),
            ],
        ),
    ]
