# Generated by Django 5.0.6 on 2024-09-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_rename_city_billing_detail_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.IntegerField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'cancelled'), ('Returned', 'Returned')], max_length=50, null=True)),
                ('total_price', models.IntegerField(blank=True, default=1, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_date', models.DateTimeField(blank=True, null=True)),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.billing_detail')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.signup')),
            ],
        ),
    ]
