# Generated by Django 5.0.6 on 2024-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancelled', 'cancelled'), ('Returned', 'Returned')], max_length=50, null=True),
        ),
    ]
