# Generated by Django 5.0.6 on 2024-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
