# Generated by Django 5.0.6 on 2024-09-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_star',
        ),
    ]
